### ISSUE TITLE
[Deepak Foundation] Prevalence of Anemia report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#11]
Report requirements:
https://docs.google.com/spreadsheets/d/1Sam_UHi3wqRNEpYcBj-gHQkjR0JTwhBl_ED-VLYpRRM/edit#gid=0

- [x] Prevalence of anemia report
- [x] Filters - Date, Location

**Comment by Dinesh2019** [comment]
Data is reflecting in the db but count is not updated in the table
