### ISSUE TITLE
[Deepak Foundation] Prevalance of menstrual Disorder Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#12]
Report Requirements:
https://docs.google.com/spreadsheets/d/1Sam_UHi3wqRNEpYcBj-gHQkjR0JTwhBl_ED-VLYpRRM/edit#gid=1461967697

- [x] Prevalence of Menstrual Disorder Report
- [x] Filters - Date, Location

**Comment by Gojo-Taqi** [comment]
ETC :- 4 hours
