### ISSUE TITLE
[Deepak Foundation] Care seeking for Menstrual disorder report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#13]
Report requirements:
https://docs.google.com/spreadsheets/d/1Sam_UHi3wqRNEpYcBj-gHQkjR0JTwhBl_ED-VLYpRRM/edit#gid=1959558046

- [x] Care seeking for Menstrual Disorder Report
- [x] Filters: Date, Location

**Comment by Gojo-Taqi** [comment]
ETC :- 3.5 hrs

**Comment by Dinesh2019** [comment]
Need a clarification according to the requirement for  Care seeking for Menstrual disorder report and Prevalence of menstrual Disorder Report the first two columns should display the same value 
1. Menstruation Started (Count of Females enrolled in Adolescent program with an answer for Menstruation started as Yes) in care the value is 46 and in prevalence, it is 50 
Care :
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/dfbf7898-a628-47d1-b2f7-a3504dd845b2)
prevalence:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/e3791205-e580-4436-be10-20ba919ed9f9)
2. likewise we have a data mismatch for disorders

**Comment by Dinesh2019** [comment]
Need a clarification according to the requirement for  Care seeking for Menstrual disorder report and Prevalence of menstrual Disorder Report the first two columns should display the same value 
1. Menstruation Started (Count of Females enrolled in Adolescent program with an answer for Menstruation started as Yes) in care the value is 46 and in prevalence, it is 50 
Care :
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/dfbf7898-a628-47d1-b2f7-a3504dd845b2)
prevalence:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/e3791205-e580-4436-be10-20ba919ed9f9)
2. likewise we have a data mismatch for disorders
