### ISSUE TITLE
[Deepak Foundation] Change decision logic for Anemia

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/Deepak-Foundation#15]
**UAT Org:**
Deepak foundation - Adolescent tracking trial
**Prod Org:**
Deepak Foundation - Adolescent Anemia tracking

- [x] Void dashboard cards which are not voided in Prod but voided in UAT.
- [x] Take latest bundle from Prod and upload on UAT.

Change decision logic for anemia as updated in this sheet:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=107721387

- [x] Update in Individual Summary
- [x] Update the decision logic for Program encounters
Baseline, Midline, Endline and Severe Anemia follow-up encounters need to be updated with the decision logic.
- [x] Update in Program Summary
- [x] Update following dashboard cards and consider Decisions and not Hb values.
1. Adolescents with Severe Anemia
2. Adolescents with Moderate Anemia
3. Adolescents with Mild Anemia
- [x] Update the Decision for existing observations through script.

**Comment by Gojo-Taqi** [comment]
Amrutha didn't call back for clarity about the ticket, hence moving this ticket back to support

**Comment by utkarshavni** [comment]
Moved this card from Support to Analysis complete as this is a change from existing Requirement.

**Comment by BEULAHEVANJALIN** [comment]
Script to update existing observations: https://gist.github.com/BEULAHEVANJALIN/a9f8705322fe9456e3c9b5c1cd2aeb52

**Comment by utkarshavni** [comment]
@BEULAHEVANJALIN  @dinesh2096 Moving this to QA failed due to issue found below.

- [ ] On updating Hemoglobin in Severe anemia follow-up from 7.9 to 11.5, the decision in form as well as program summary was not updated. Access recording from below given link.
https://drive.google.com/drive/u/0/folders/1qEh-md_lLM1IKbOi0T_omcGLukoZ-m6D

**Comment by Dinesh2019** [comment]
@utkarshavni if we select the no option for this question (Was hemoglobin tested after last follow-up?) we should have the value auto populate and it should be ready only but we are not supporting we have it as editable so the status is not updated if we have the option as yes the scenario works fine.

https://images.zenhubusercontent.com/639871834/ec00879e-4fce-4ee1-a965-f08e97a53adc/untitled.mp4
