### ISSUE TITLE
[Deepak Foundation] Provide options to select in Filter for School

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#18]
**Use case**
The existing filter of School in all the reports is free-text. This does not allow user to select a School and user is required to provide a text that matches with the exact text provided in the location name which is not feasible.

Metabase folder name for Reports: **dfad tracking**

**Goal:**
- [x] Provide an option for user to select one or multiple schools from a given list.

**Acceptance criteria:**
User should be able to select one or multiple locations and applying the filter should bring the data only for selected schools.

**Comment by utkarshavni** [comment]
@BEULAHEVANJALIN  @nupoorkhandelwal   moving this card to Ready since we need to change the existing solution and provide School list from locations.

**Comment by Dinesh2019** [comment]
Test Scenarios :

1. Validate the data without filters
2. Apply the school filter for one school
3. Apply the for more than one school
4. Edit the filter for one school
5. change the filter for the other two to school which was not selected in the previous location
6. remove the filters and validate the data
