### ISSUE TITLE
[Deepak Foundation] - Upload bundle for required forms for SEWA Rural and make changes in the forms

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#3]
- [x] Download bundle from Adolescent Sewa Rural - do not include locations.
- [x] Upload the bundle with only following forms - 
1.  Individual registration
2.  Adolescent program enrollment and exit
3.  Annual visit - baseline (program encounter)
4.  Annual visit - endline (program encounter)
5.  Severe anemia follow-up (program encounter)
6.  Menstrual absenteeism follow-up (program encounter)
- [x] Change Location level at which Individual is registered to school.
- [x] Individual registration form to have following questions:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=2140030636
- [x] Rename Annual visit - Baseline as "Baseline screening" and only keep the questions refereed in the sheet:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=1605263137
- [x] Rename "Annual visit -endline as  "Endline screening" and only keep the questions refereed in the sheet:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=450962261
- [x] Severe Anemia follow-up form
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=438616642
- [x] Menstrual absenteeism follow-up form:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=1650116831

**Comment by Gojo-Taqi** [comment]
ETC :- 3 hrs

**Comment by Dinesh2019** [comment]
- [x] under Baseline BMI (kg/m2)(14.5 - 24.9) but in the requirement sheet we have the range as (18.5 - 24.9)
- [x] Under Baseline screening as per the requirement sheet the HB range for 1 -20 but we added the range as 8-20
- [x] From where as per the requirement we have the deepak as an option but we add sewa rural
- [x] BMI should be mandatory filed 
- [x] Albendazole tablets received is not in requirement sheet but we have added in app
- [x] under female medical history for this field Absorbent material used most of the times it is single select as per the requirement we have used it as multi field
- [x] same as well for Menstrual disorder
- [x] same as well for Reason for remaining absent during menstruation
- [x] we don't have the MHM kit is the requirement but we have it in the app 
- [x] under Addition medical history Sickness in last 1 months we have single select in requirement but we have multi select in the app 
- [x] Do you suffer from burning micturition? as per the requirement it should displayed only if the adolescent is married but it showing even the adolescent married as no
- [x] Do you suffer from Ulcer over genitalia? same as well 
- [x] Do you suffer from Yellowish discharge from Vagina / penis? same as well
- [x] Any treatment should be single select
- [x] Reason for remaining absent during menstruation should be single select
- [x] need to check on the counseling points

**Comment by Dinesh2019** [comment]
QA Feedback
------------------------
- [x] If the individual is exited from the program by reason of death I think we remove the enroll option in the program 
- [x] We need to schedule the Severe Anemia and Menstrual Absenteeism Followup after we complete the mid line schedule and also confirm with Utkarsh

**Comment by utkarshavni** [comment]
@dinesh2096 moving this to QA failed.

**Comment by Gojo-Taqi** [comment]
@Dinesh2019 menstrual absenteeism cannot be schedule on midline as there are no questions related to that in this encounter
