### ISSUE TITLE
[Deepak foundation] User is able to record blood sample results for severely anemic

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#4]
- [x] Create a program encounter "Record blood sample result"
- [x] Form requirements:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=494539049

**Comment by utkarshavni** [comment]
Have updated ranges in the validation column.
Show helptext as explained in the Logic column with the help of documentation feature. Show the text in Red.
@Gojo-Taqi  @dinesh2096   moving this card to Ready.

**Comment by Dinesh2019** [comment]
- [x] For Blood count Total RBC count we are missing the range (3.8 to 4.8)
- [x] Neutrophils (%) we are missing the range (40 to 80)
- [x] For the Blood sample result according to the requirement sheet we have the question names as Sample collected for CBC? if the answer to this is yes then we have to show the below fields  Blood count,Blood Indices:,Diffrential leococyte count and Changes in dose suggested by dr if not we can hide the question.

**Comment by Gojo-Taqi** [comment]
Fixed the issues, moving the card back to QA ready
