### ISSUE TITLE
[Deepak foundation] Offline dashboard

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#6]
Dashboard requirements:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=984267394

Create following cards:
- [x] Total adolescents screened
- [x] Total adolescents enrolled
- [x] Adolescent with mild anemia
- [x] Adolescent with moderate anemia
- [x] Adolescent with severe anemia
- [x] Adolescents who dropped out
- [x] Adolescents having chronic sickness

**Comment by Gojo-Taqi** [comment]
ETC :- 2 hrs

**Comment by Dinesh2019** [comment]
- [ ] Need a calrification we have enrolled the individual in the adolescent program we have the value as 1 for this  Total adolescents enrolled and if done the screening for that individual we have the count as 1 for Total adolescents screened 
i think if done the screening we can remove the individual for the Total adolescents enrolled and we can show like this 
excepted :  Total adolescents enrolled - 0 and Total adolescents screened -1 
Actual : Total adolescents enrolled - 1 and Total adolescents screened -1 
discussed with utkarsh will have the separate card for this

**Comment by Dinesh2019** [comment]
If we edit the individual from mild to severe anemia the dashboard is not updated.
https://images.zenhubusercontent.com/639871834/3fdec89e-fcf5-4f41-bee8-94ee0b673091/record_2023_06_08_17_16_58.mp4

**Comment by Gojo-Taqi** [comment]
Fixed the issues, moving the card back to QA ready
