### ISSUE TITLE
[Deepak Foundation] User is able to record midline screening details

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#7]
- [x] Create a program encounter named "Midline screening"
- [x] Schedule it 3 months after Baseline is done.
- [x] Form requirements:
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=1846320309
- [x] Schedule Endline after 3 months of Midline, when Midline is completed.
- [x] If Blood sample collected is Yes in Midline screening, then schedule Record Blood sample result encounter after a week.

**Comment by Gojo-Taqi** [comment]
ETC :- 45 mins

**Comment by Dinesh2019** [comment]
- [ ] Missing the logic in the Record blood sample result
- [ ] we have the separate card for this above issue| https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/deepak-foundation/4

**Comment by utkarshavni** [comment]
@dinesh2096 move this card to Deploy ready if QA is done successfully. We will only keep Epics in "Ready for review" lane, not the issues.
