### ISSUE TITLE
[Deepak Foundation] Feedback items from demo

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#8]
- [x] Add following baseline questions in the registration form
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=2140030636
- [x] Auto populate the above values in the baseline from Registration form.
- [x] Show Subject Summary as shown in the sheet after registration
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=107721387
- [x] Home visit done question to non mandatory in Follow-up forms
- [x] Only allow those individuals to be eligible for program who are Mild, Moderate or Severe Anemia
- [x] Following questions to be added in Baseline, Midline, Endline and Severe Anemia follow-up - refer to the green highlighted cells
https://docs.google.com/spreadsheets/d/1h_eQJRhAN-SSWXoCfpN74o0RAqC0ajHTkrZUh8hPk_c/edit#gid=1605263137
- [x] The program summary should display Moderate, severe and Mild anemia based on the Hb values. Logic to be same as Subject summary.

- [x] Dashboard changes:
- Adolescents screened - to show all the registered adolescent count
- Adolescents enrolled in program - show count of only the ones enrolled in program
- Add new card for "Adolescents - Menstrual absenteeism" - show count of all the adolescents for whom "Do you remain absent in school during menstruation" answer is Yes.

**Comment by Dinesh2019** [comment]
- [x] Sickling Test result is not showing
- [x] for non anemica we can able to enroll
- [x] BMI status is missing in the profile summary
- [x] Sickling Test Status is missing in endline
- [x] Sickling Test Result is missing in endline
